name: Build Devzat

on:
  push:
    branches:
      - main # Make sure we don't push bad code to main
  pull_request:

jobs:
  build_devzat:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
        check-latest: true
    - run: go build # just build for now to verify code compiles, any tests can run here too
    - run: go test
    
